// Code generated by "stringer -type=EtcdMemberState"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Leader-0]
	_ = x[Follower-1]
	_ = x[Learner-2]
	_ = x[Unknown-3]
}

const _EtcdMemberState_name = "LeaderFollowerLearnerUnknown"

var _EtcdMemberState_index = [...]uint8{0, 6, 14, 21, 28}

func (i EtcdMemberState) String() string {
	if i < 0 || i >= EtcdMemberState(len(_EtcdMemberState_index)-1) {
		return "EtcdMemberState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EtcdMemberState_name[_EtcdMemberState_index[i]:_EtcdMemberState_index[i+1]]
}
